### ISSUE TITLE
JOSS

### ISSUE THREAD

**Issue by suriya-ganesh** [JIBSIL/DistriFS#5]
Hi @JIBSIL ,

Thank for this project!

I'm opening this issue to track my review in your repo.
These are my part my observations and part JOSS requirements.

### JOSS Requirements

- [x] Automated unit/integration/e2e Tests for the system you've developed. 
- [x] Community Guidelines , while this is a fairly straightforward project and contributing would be easy. It's nicer for new people to have these guidelines

###  Personal Observations
- The justification and failure reasons for BitTorrent as well as IPFS is very interesting and reasonable. But I'm curious, with way that DistriFS is setup right now how is it "distributed"? how would a new server coming up, discover other servers in the network? how would they share files? how does encryption work in that scenario?
- I spent some time with the code, but couldn't confirm that there were any authorization system for downloading or uploading the file. Would love to know if I'm wrong. If not, what is the logic behind having a cryptography scheme and back and forth?

JOSS issue thread: https://github.com/openjournals/joss-reviews/issues/6625

**Comment by JIBSIL** [comment]
@suriya-ganesh - To answer your questions:
- In regards to being distributed: People who wish to download from the network can operate an indexer or use somebody else's. The person who runs the indexer creates a list of indexers which their indexer receives names and hashes from, which is displayed to the client when calling the getAllFiles route (this is inefficient when many files are present in the indexer; I plan to add a different system for retrieving servers in the next release). The client can specify a filename or hash to search for, and they get a download link to the server.
- A new server (by this I assume you mean indexer/server combination) coming up would be able to connect to any popular indexer (if this system were to see popular use, I'm sure there would be popular ones or some listing) and get a recursive file listing of every file on every indexer that is known to that first indexer. Additionally, the suggestServer endpoint can be called by anyone (e.g a server listing website?) to suggest a new server to the indexer.
- Files are stored exclusively on servers. Indexers just point to them; the user discovers the file to download based on the outputs of an indexer.
- There is actually no system for uploading files sent by users. However the "passport" system allows the server owner to restrict access to certain files by public key (this is mentioned in further detail [in the server README](https://github.com/JIBSIL/DistriFS/tree/main/server#authenticating)). The server owner may then set their public key in the `AdminKeys` section or password-protect certain files through this syntax:
```yaml
PassportProtectedFiles:
  test.txt:
    - mypublickey
    - secondkey
```
(as shown in [config.go](https://github.com/JIBSIL/DistriFS/blob/main/server/modules/helper/config.go) of the server)

**Comment by JIBSIL** [comment]
I have just made some changes to the Contributing section through [this commit](https://github.com/JIBSIL/DistriFS/commit/27f5959f14bcc91936d3a19d836727a5af76345b) and [this commit](https://github.com/JIBSIL/DistriFS/commit/7681208053529a4c3d5546ebf542283b6fb6e6e0). I hope this passes the community guidelines check. I will work on rewriting my tests into native Go this week. Thanks for your review!
- JIBSIL

**Comment by suriya-ganesh** [comment]
Ah! I see, thank you for your answers.
This is great!! I didn't notice the indexer routes.
Awesome work @JIBSIL 
LMK once you fix the tests, I'll approve them together and we should be good.

**Comment by JIBSIL** [comment]
<img width="817" alt="image" src="https://github.com/JIBSIL/DistriFS/assets/40243545/a3ee3550-57a7-42f9-ad16-a5d80071fa2f">
<img width="436" alt="image" src="https://github.com/JIBSIL/DistriFS/assets/40243545/1ff04cb7-5a7e-47ce-818f-bb449f25572e">

**Comment by JIBSIL** [comment]
Added testing as of [commit 63b61d4](https://github.com/JIBSIL/DistriFS/commit/63b61d4071a62edf792db49daf30bfe8cf866702). Testing instructions are also added to README so users can replicate the results above.

**Comment by aparoha** [comment]
Thanks for adding tests and readme.

**Comment by JIBSIL** [comment]
Closing issue as the paper has been published in JOSS
